using Roblox.Platform.Localization.Audit;

namespace Roblox.Platform.Localization.Accounts;

internal interface IAccountCountriesAuditMetadataTypeConverter
{
	byte GetEntityIdFromEnum(AccountCountriesAuditEntryMetadataType metadataType);

	AccountCountriesAuditEntryMetadataType GetEnumFromEntity(IAccountCountriesAuditMetadataTypeEntity metadataTypeEntity);
}
