namespace Roblox.TranslationResources.Communication;

public interface ICommonEmailResources : ITranslationResources
{
	/// <summary>
	/// Key: "Description.MessageGenerationContent"
	/// The environment specific generation message appended to each email.
	/// English String: "This message was generated by {environmentIdentifier}."
	/// </summary>
	string DescriptionMessageGenerationContent(string environmentIdentifier);
}
